{
 "title": "Power Consumption",
 "tags": [
  "cisco",
  "UCS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "Database", "query": "telegraf" },
   { "name": "rp", "label": "Retention Policy", "query": "autogen" },
   { "name": "data_source", "label": "Data Source", "query": "influxdb" },
   {
    "name": "ucs_domain",
    "query": "select (domain) from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"FIEnvStats\" GROUP BY domain)"
   },
   {
    "name": "fabric_interconnect",
    "query": "select (fi_id) from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"FIEnvStats\" GROUP BY fi_id)"
   },
   {
    "name": "chassis",
    "query": " select (chassis_id) from (SELECT last(\"power_psu1\") FROM \"$db\".\"$rp\".\"ChassisEnv\" WHERE \"domain\" =~ /^$ucs_domain$/ GROUP BY chassis_id)"
   },
   {
    "name": "servers",
    "query": "select id from (SELECT last(\"model\") FROM \"$db\".\"$rp\".\"Servers\" WHERE \"domain\"=~ /^$ucs_domain$/ GROUP BY domain,chassis,type,id)"
   },
   {
    "name": "location",
    "label": "Location",
    "query": "show tag values from \"$db\".\"$rp\".\"Servers\" with key=location "
   },
   { "name": "polling_interval", "query": "60.0" },
   {
    "name": "num_locations",
    "query": " SHOW TAG VALUES CARDINALITY FROM \"$db\".\"$rp\".\"FIEnvStats\" WITH KEY=location"
   },
   { "name": "fc_data_rate", "query": "0.85" },
   { "name": "5m_in_ms", "query": "300000" },
   {
    "name": "utm_collector_ver",
    "query": "select last(utm_collector_ver) from \"$db\".\"$rp\".\"FIEnvStats\""
   },
   {
    "name": "average_ucs_domain_total_power",
    "query": "SELECT  MEAN((\"total_power\")) FROM \"DomainEnvStats\" WHERE \"domain\"=~ /^$ucs_domain$/ AND $timeFilter\n"
   },
   {
    "name": "average_chassis_total_power",
    "query": "SELECT  MEAN((\"total_power\")) FROM \"ChassisEnv\" WHERE (\"domain\" =~ /^$ucs_domain$/ AND \"chassis_id\" =~ /^$chassis$/)  AND $timeFilter\n\n"
   },
   {
    "name": "average_fi_total_power",
    "query": "SELECT  MEAN((\"total_power\")) FROM \"FIEnvStats\" WHERE (\"fi_id\" =~ /^$fabric_interconnect$/ AND \"domain\" =~ /^$ucs_domain$/)  AND $timeFilter\n\n\n"
   },
   {
    "name": "average_server_total_power",
    "query": "SELECT  MEAN((\"power_consumed\")) FROM \"Servers\" WHERE \"domain\" =~ /^$ucs_domain$/  AND \"id\" =~ /^$servers$/ AND \"chassis\" =~ /^$chassis$/ AND $timeFilter \n\n\n\n"
   }
  ]
 },
 "panels": [
  { "title": "UCS Domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UCS Domain Power Consumption ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_domain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DomainEnvStats",
     "query": "SELECT mean(\"total_power\") FROM \"DomainEnvStats\" WHERE (\"domain\" =~ /^$ucs_domain$/) AND $timeFilter GROUP BY time($__interval), \"domain\"",
     "select": [
      [
       { "params": [ "total_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$ucs_domain$/" }
     ]
    },
    {
     "alias": "average power consumption $ucs_domain",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT meanValues + $average_ucs_domain_total_power FROM (SELECT (mean(\"total_power\") - mean(\"total_power\"))  as meanValues  FROM \"DomainEnvStats\"  GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$ucs_domain ucs domain average total power consumption (per domain)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT meanValues + $average_ucs_domain_total_power FROM (SELECT (mean(\"total_power\") - mean(\"total_power\"))  as meanValues  FROM \"DomainEnvStats\"  GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Fabric Interconnects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fabric Interconnects Power Consumption ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_domain $tag_fi_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "fi_id" ], "type": "tag" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FIEnvStats",
     "query": "SELECT mean(\"total_power\") FROM \"FIEnvStats\" WHERE (\"fi_id\" =~ /^$fabric_interconnect$/ AND \"domain\" =~ /^$ucs_domain$/) AND $timeFilter GROUP BY time($__interval), \"fi_id\", \"domain\" fill(null)",
     "select": [
      [
       { "params": [ "total_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "fi_id", "operator": "=~", "value": "/^$fabric_interconnect$/" },
      { "condition": "AND", "key": "domain", "operator": "=~", "value": "/^$ucs_domain$/" }
     ]
    },
    {
     "alias": "average power consumption $ucs_domain $fabric_interconnect",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT meanValues + $average_fi_total_power FROM (SELECT (mean(\"total_power\") - mean(\"total_power\"))  as meanValues  FROM \"FIEnvStats\"  GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Chassis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Chassis Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_domain $tag_chassis_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "chassis_id" ], "type": "tag" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ChassisEnv",
     "query": "SELECT mean(\"total_power\") FROM \"ChassisEnv\" WHERE (\"domain\" =~ /^$ucs_domain$/ AND \"chassis_id\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"/^$chassis$/\" fill(none)",
     "select": [
      [
       { "params": [ "total_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$ucs_domain$/" },
      { "condition": "AND", "key": "chassis_id", "operator": "=~", "value": "/^$chassis$/" }
     ]
    },
    {
     "alias": "average power consumption $ucs_domain $chassis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT meanValues + $average_chassis_total_power FROM (SELECT (mean(\"total_power\") - mean(\"total_power\"))  as meanValues  FROM \"ChassisEnv\"  GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Server Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_domain $tag_chassis $tag_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "domain" ], "type": "tag" },
      { "params": [ "id" ], "type": "tag" },
      { "params": [ "chassis" ], "type": "tag" }
     ],
     "measurement": "Servers",
     "query": "SELECT mean(\"power_consumed\") FROM \"Servers\" WHERE (\"domain\" =~ /^$ucs_domain$/ AND \"id\" =~ /^$servers$/ AND \"chassis\" =~ /^$chassis$/) AND $timeFilter GROUP BY time($__interval), \"domain\", \"id\", \"chassis\"",
     "select": [
      [
       { "params": [ "power_consumed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "domain", "operator": "=~", "value": "/^$ucs_domain$/" },
      { "condition": "AND", "key": "id", "operator": "=~", "value": "/^$servers$/" }
     ]
    },
    {
     "alias": "average power consumption $ucs_domain $chassis $servers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT meanValues + $average_server_total_power FROM (SELECT (mean(\"power_consumed\") - mean(\"power_consumed\"))  as meanValues  FROM \"Servers\"  GROUP BY time($__interval))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}